name: FC70 CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Actions checkout
      uses: actions/checkout@v3

    - name: Docker cli setup
      uses: docker/setup-buildx-action@v2

    - name: Login Docker Registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Frontend Image
      run: |
        docker build -t brdekrom/fashionclub-frontend:latest -f ./FashionClub/FashionClub.frontend/fc70/Dockerfile ./FashionClub/FashionClub.frontend/fc70
        docker push brdekrom/fashionclub-frontend:latest

    - name: Push API Image
      run: |
        docker build -t brdekrom/fashionclub-api:latest -f ./FashionClub/Dockerfile ./FashionClub
        docker push brdekrom/fashionclub-api:latest

    - name: Deploy Azure
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        port: 22
        script: |
          cd /fc70
          docker-compose pull
          docker-compose up -d
